import { defineStore } from 'pinia'
import { useLocalStorage } from '@vueuse/core'


export const useGlobalStore = defineStore('global', {
    state: () => ({
        node: null,
        IPFSStatus: false,
        // auth: useLocalStorage('auth', false),
        // userName: useLocalStorage('userName', ''),
        // currency: useLocalStorage('currency', 'BTC')
        auth: false,
        userName: '',
        currency: 'BTC',
        wallets: {},
        avatar: '',
        tooltip: '',
        balance_usdt: 0,
        balance_atom: 0,
        balance_eth: 0,
        balance_btc: 0,
        personal_APR: 0,
        RPDE: 0,
        networks: {
            'cosmos': {
                status: false,
                health: 0,
                health_color: 'grey',
                apr: 0,
                speed: 0,
                delegations_sum: 0,
                validators: [],
                total_annual_provision: 0,
                RPDE: 0,
                personal_APR: 0,
                price: 0,
                price_usdt: 0,
                price_atom: 0,
                price_eth: 0,
                price_btc: 0
            },
            'bostrom': {
                status: false,
                health: 0,
                health_color: 'grey',
                apr: 0,
                speed: 0,
                availabel: 0,
                availabel_percents: 0,
                delegations_sum: 0,
                validators: [],
                total_annual_provision: 0,
                RPDE: 0,
                personal_APR: 0,
                price: 0,
                price_usdt: 0,
                price_atom: 0,
                price_eth: 0,
                price_btc: 0
            },
            'osmo': {
                status: false,
                health: 0,
                health_color: 'grey',
                apr: 0,
                speed: 0,
                delegations_sum: 0,
                validators: [],
                total_annual_provision: 0,
                RPDE: 0,
                personal_APR: 0,
                price: 0,
                price_usdt: 0,
                price_atom: 0,
                price_eth: 0,
                price_btc: 0
            },
            'juno': {
                status: false,
                health: 0,
                health_color: 'grey',
                apr: 0,
                speed: 0,
                delegations_sum: 0,
                validators: [],
                total_annual_provision: 0,
                RPDE: 0,
                personal_APR: 0,
                price: 0,
                price_usdt: 0,
                price_atom: 0,
                price_eth: 0,
                price_btc: 0
            },
            'emoney': {
                status: false,
                health: 0,
                health_color: 'grey',
                apr: 0,
                speed: 0,
                delegations_sum: 0,
                validators: [],
                total_annual_provision: 0,
                RPDE: 0,
                personal_APR: 0,
                price: 0,
                price_usdt: 0,
                price_atom: 0,
                price_eth: 0,
                price_btc: 0
            },
            'stars': {
                status: false,
                health: 0,
                health_color: 'grey',
                apr: 0,
                speed: 0,
                delegations_sum: 0,
                validators: [],
                total_annual_provision: 0,
                RPDE: 0,
                personal_APR: 0,
                price: 0,
                price_usdt: 0,
                price_atom: 0,
                price_eth: 0,
                price_btc: 0
            },
            'gravity': {
                status: false,
                health: 0,
                health_color: 'grey',
                apr: 0,
                speed: 0,
                delegations_sum: 0,
                validators: [],
                total_annual_provision: 0,
                RPDE: 0,
                personal_APR: 0,
                price: 0,
                price_usdt: 0,
                price_atom: 0,
                price_eth: 0,
                price_btc: 0
            },
            'evm': {
                status: false,
                health: 0,
                health_color: 'grey',
                apr: 0,
                speed: 0,
                delegations_sum: 0,
                validators: [],
                total_annual_provision: 0,
                RPDE: 0,
                personal_APR: 0,
                price: 0,
                price_usdt: 0,
                price_atom: 0,
                price_eth: 0,
                price_btc: 0
            },
            'cre': {
                status: false,
                health: 0,
                health_color: 'grey',
                apr: 0,
                speed: 0,
                delegations_sum: 0,
                validators: [],
                total_annual_provision: 0,
                RPDE: 0,
                personal_APR: 0,
                price: 0,
                price_usdt: 0,
                price_atom: 0,
                price_eth: 0,
                price_btc: 0
            },
            'omniflix': {
                status: false,
                health: 0,
                health_color: 'grey',
                apr: 0,
                speed: 0,
                delegations_sum: 0,
                validators: [],
                total_annual_provision: 0,
                RPDE: 0,
                personal_APR: 0,
                price: 0,
                price_usdt: 0,
                price_atom: 0,
                price_eth: 0,
                price_btc: 0
            },
            'desmos': {
                status: false,
                health: 0,
                health_color: 'grey',
                apr: 0,
                speed: 0,
                delegations_sum: 0,
                validators: [],
                total_annual_provision: 0,
                RPDE: 0,
                personal_APR: 0,
                price: 0,
                price_usdt: 0,
                price_atom: 0,
                price_eth: 0,
                price_btc: 0
            }
        }
    })
})
